<?php

// Include your classes (usually from a separate files)

class Dog {

  public $name;
  public $bark_hook_init;
  public $bark_hook_boot;
  public function bark(){ drupal_set_message ("The dog $this->name barks."); }

  public $eat_hook_boot;
  public function eat(){ drupal_set_message ("The dog $this->name eats."); }

  public function __construct($name){ $this->name = $name; }
}



class Cat {
  
 public $name;
 public $meow_hook_init;
 public function meow(){ drupal_set_message ("The cat $this->name meows."); }

 public function __construct($name){ $this->name = $name; }

}


// Instantiate your classes - create objects
$dog1 = new Dog("Rufus"); $dog2 = new Dog("Basil"); $cat = new Cat("Matilda");

// Tell DrupalizeClass the name of your module
DrupalizeClass::setModuleName("drupalize_class_example");

//Tell DrupalizeClass that your objects should listen to hooks
DrupalizeClass::regHooks($dog1, $dog2, $cat);
